version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/quickmart
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/quickmart
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migrations
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - JWT_PUBLIC_KEY=classpath:public.pem
      - JWT_PRIVATE_KEY=classpath:key.pem
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: quickmart
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/ninho/Documents/dump-sql/quickmart:/dump

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: quickmart

volumes:
  mysql_data:
  mongo_data:
