spring:
    servlet:
        multipart:
            max-request-size: 10MB
            max-file-size: 10MB
            enabled: true
    data:
        mongodb:
            uri: mongodb://localhost:27017/quickmart
    datasource:
        url: jdbc:mysql://localhost:3307/quickmart
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            auto-commit: true
            connection-timeout: 30000
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migrations
        baseline-on-migrate: true
jwt:
    public-key: classpath:public.pem
    private-key: classpath:key.pem