spring:
    datasource:
        url: jdbc:mysql://localhost:3306/quickmart
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            auto-commit: true
            connection-timeout: 30000
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migrations
        baseline-on-migrate: true
jwt:
    public-key: classpath:public.pem
    private-key: classpath:key.pem